### PR TITLE
Add creation of updated_speed.html and temp folder if missing

### PR DESCRIPTION
**Pull request by exadeci**
Hello,
I was trying to use this project and had some issues to get the examples running so I fixed them and here's the result.

- add creation of updated_speed.html if missing
- add base dom to the templates to avoid a wkhtmltoimage error
- change missing sample data to an exisiting one

### CODE REVIEW

**Comment by Seangottarun** [comment]
Hi @exadeci, thanks for putting together this pull request! It looks good, but I'll try it out sometime tonight or tomorrow before merging it in. It's been awhile since I last worked on this, so I'll need to familiarize myself with the code again.

Just for future reference so I know what to prioritize/test first, what operating system and `python3` version are you using? Also, are you planning to use `GPXOverlay` with real video and GPS data? If so, what sport/activity are you doing and which types of GPS data (ex. speed, elevation, location) will you be using?

If you're planning to use this project further, there's a few key functionalities that are missing. I realized that I will also be needing to use this for something else, so I'm planning to put in some work this week to fix it up. If you're interested, we can maybe split up the work below. Off the top of my head, here's the fixes/features that I want to add:

1. Add interpolation (**must include**)
- The sample rate of the GPS (ex. `1 Hz`), does not match the `FPS` of a video 
    - That's why the data overlay will suddenly stop before the video is finished
    - If you put your own GPS data and video (each recorded at the same time), they will not be synced up
- Other GPS software will interpolate the data, so I'm thinking of using `ffmpeg-python` to get the `FPS` of the input video and then use `numpy` to interpolate the data in between GPS samples
2. Make `GPXOverlay` into a local `pip` package 
- So that imports are easier and `python3 -m examples.overlay_speed.py` is no longer needed
3. Find a way to speed up the video processing
- Maybe there's a way to parellelize the processing?
- The HTML to PNG conversion was pretty slow, so if you don't need that feature, then it could easily sped up

**Comment by exadeci** [comment]
Hey, 

I'm running it on MacOs Catalina and using Python 3.8.5.
I tested it yesterday with a motorcycle-riding video so mostly speed and maybe location.
I did notice the overlay stopping but assumed that my gpx data was broken.
Also, the speed wasn't converted properly it was all 1.xxx even though the source is m/s see:
speed171

Side note I had to change https://github.com/Seangottarun/GPXOverlay/blob/master/GPXOverlay/analysis.py#L30
`trkseg = root[1][2]` to `trkseg = root[1][1]` for it to work with my data, not sure of what would be the best approach for that maybe using the names.


Happy to give you hand. I could look into parallel processing.

**Comment by Seangottarun** [comment]
Cool! Thanks for helping out!

Regarding the `trkseg = root[1][2]` to `trkseg = root[1][1]` issue for https://github.com/Seangottarun/GPXOverlay/blob/master/GPXOverlay/analysis.py#L30, our GPX files may be slightly different. If you don't mind, can you open up a new issue and share your GPX file with the first few `<trkpt>` elements? You can replace all the location data with random numbers for privacy. I just need the general structure of the GPX file. I definitely agree with you that the current approach with the indices is not ideal. 

I'll also check the m/s issue this week after I collect some new test data on my end.

**Comment by Seangottarun** [comment]
I tested your additions with `python3 -m examples.overlay_speed.py` and they work well. I also added a few lines to make the `temp/` folder if it doesn't exist.

When I tried the `overlay_elevation.py` example, I ran into some other issues unrelated to your work. I don't have any need for elevation data right now, so I think I'll postpone that work until later.

**Pull request merged**
